myshop/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls import include
#from django.conf.urls import include, url

from django.conf import settings
from django.conf.urls.static import static

from users import views as user_views
from django.contrib.auth import views as auth_views

from shop import views as shop_views

from django.urls import re_path
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    #path(r'^admin/', include(admin.site.urls)),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/',
         auth_views.LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('logout/',
         auth_views.LogoutView.as_view(template_name='users/logout.html'),
         name='logout'),
    path(r'cart/', include('shopping_cart.urls')),
    #url(r'^cart/', include('cart.urls', namespace='cart')),
    path(r'orders/', include('shopping_orders.urls')),
    #path(r'^orders/', include('shopping_orders.urls')),
    #url(r'^orders/', include('orders.urls', namespace='orders')),
    path(r'', include('shop.urls')),
    #path(r'', include('shop.urls', namespace='shop')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#for working image at Debug=False
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT,}),]

shop/urls.py
from django.contrib import admin
from django.urls import path, include

#from django.conf.urls import url
from . import views

app_name = 'shop'
urlpatterns = [
    path(r'', views.product_list, name='product_list'),
    path(r'about/', views.about, name='about'),
    #path(r'^$', views.product_list, name='product_list'),
    path(r'(?P<category_slug>[-\w]+)/',
        views.product_list,
        name='product_list_by_category'),
    path(r'(?P<id>\d+)/(?P<slug>[-\w]+)/',
        views.product_detail,
        name='product_detail'),
    path('Search/', views.Search.as_view(), name='Search'),
    #path('SearchProducts/', views.SearchProducts.as_view(), name='SearchProducts'),
    path('SearchNames/', views.SearchNamesView.as_view(), name='SearchNames'),

]

'''
urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list,
        name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),
]
'''

shopping_cart/urls.py
#from django.conf.urls import url
from django.urls import path, include
from . import views


app_name = 'shopping_cart'
urlpatterns = [
    path(r'', views.cart_detail, name='cart_detail'),
    path(r'add/(?P<product_id>\d+)/', views.cart_add, name='cart_add'),
    #path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    path(r'remove/(?P<product_id>\d+)/', views.cart_remove, name='cart_remove'),
    #path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

shop/models.py
from django.db import models

# Create your models here.
from django.urls import reverse


class Category(models.Model):
    """Category of goods our shop."""
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категорія'
        verbose_name_plural = 'Категорії'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])


class Product(models.Model):
    """Detail description of goods."""
    category = models.ForeignKey(Category,
                                 on_delete=models.CASCADE,
                                 related_name='products')
    name = models.CharField(max_length=50,
                            db_index=True,
                            verbose_name="Найменування")
    slug = models.SlugField(max_length=200,
                            db_index=True)  #аліас продукта(його URL)?
    code = models.PositiveIntegerField(blank = True,
                                       verbose_name="артикул")
    stock = models.PositiveIntegerField(default=100,
                                        verbose_name="кількість товара") #default=100 for 'simply inputing'
    available = models.BooleanField(default=True,
                                    verbose_name="наявність товара")
    price = models.DecimalField(max_digits = 8,
                                decimal_places = 2,
                                verbose_name="ціна товара") #222222.22
    description = models.TextField(max_length=2000,
                                   blank = True,
                                   verbose_name="опис товару")
    image = models.ImageField(upload_to='media',
    #image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank = True,
                              verbose_name="фотографія товара")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    '''integer_field           = models.IntegerField()
    positive_small_field    = models.PositiveSmallIntegerField()
    big_integer_field       = models.BigIntegerField()
    float_field             = models.FloatField()
    binary_field            = models.BinaryField()
    file_field              = models.FileField(upload_to = 'file')'''
    #onsale = models.ManyToManyField(Sale)
    #user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ('name',)
        # задаємо індекс для полів, тя будемо запитувати продукти за допомогою id та slug
        index_together = (('id', 'slug'),)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товари'

    def __str__(self):
        return f"Назва : {self.name} Артикул : {self.code} Наявність : {self.available}"

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])


class CommentModel(models.Model):
    """Users anonimus comment of goods."""
    product = models.ForeignKey(Product,
                             on_delete=models.CASCADE,
                             related_name='comments',
                             verbose_name="коментар товару")
    #name = models.CharField(max_length=80)
    #email = models.EmailField()
    body = models.TextField(verbose_name="відгук")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True) #for moderate comment

    class Meta:
        ordering = ('created',)
        verbose_name = 'Відгук'
        verbose_name_plural = 'Відгуки'

    def __str__(self):
        return f'Відну авторизованого користувача до {self.product}'


'''
class User(models.Model):
    name = models.CharField(max_length=10, blank = True, verbose_name = "Ім'я")
    surname = models.CharField(max_length=15, blank = True, verbose_name="Прізвище", null=True)
    email = models.EmailField(blank = True)
    date_time_buy = models.DateTimeField(auto_now_add=False, verbose_name="дата покупки", null=True)
    LastBuy = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"Ім'я : {self.name} Прізвище : {self.surname}"

    class Meta:
        verbose_name = "Користувач"
        verbose_name_plural = "Користувачі"
'''

shop/forms.py
from django import forms

from .models import CommentModel


class CommentForm(forms.ModelForm):
    """Form of comment goods."""
    class Meta:
        model = CommentModel
        fields = ('body', )
        #fields = ('name', 'email', 'body')

shop/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import get_object_or_404
from .models import Category, Product, CommentModel
from shopping_cart.forms import CartAddProductForm

from .forms import CommentForm
#for search (from DZ_CBS33)
from django.views.generic import TemplateView, ListView
from django.db.models import Q

def product_list(request, category_slug=None):
    """ Загальний список (наявних) товарів."""
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


'''def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    return render(request,
                  'shop/product/detail.html',
                  {'product': product})'''


def product_detail(request, id, slug):
    """ Опис (наявної) одиниці товару."""
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()  #кнопка дадати в кошик

    comments = product.comments.filter(active=True)  #використовуємо related_name з моделі CommentModel
    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        print(f'test comment1: {comment_form}')
        if comment_form.is_valid():
            print(f'test comment2: {comment_form}')
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.product = product
            # Save the comment to the database
            new_comment.save()
            print(f'test comment3: {comment_form}')
    else:
        comment_form = CommentForm() # for metod GET

    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form,
                   'comments': comments,
                   'comment_form': comment_form})


def about(request):
    """Publication of general information about project/company"""
    return render(request,'shop/about.html', {})

#(from DZ_CBS33)
class Search(TemplateView):
    """Product search by keyword (part of) in name, description DB (will be update for many fields)."""
    template_name = 'shop/search.html'
    def post(self , request):
        query = request.POST['search']
        result_list  = Product.objects.filter(Q(name__icontains=query) | Q(description__icontains=query))
        #result_list = Product.objects.filter(name=query)

        if result_list.count() != 0:
            context = {
                'result_list': result_list,
                'query': query,
            }
        else:
            context ={
                'empty': "Нічого не найдено :(",
                'query': query,
            }
        return render(request , 'shop/search_results.html' , context)


'''class SearchProducts(TemplateView):
    """Product search by name in DB."""
    template_name = 'shop/base.html'
    def post(self , request):
        query = request.POST['search']
        result_list  = Product.objects.filter(name=query)
        if result_list.count() != 0:
            context = {
                'result_list': result_list,
                'query': query,
            }
        else:
            context ={
                'empty': "Нічого не найдено :(",
                'query': query,
            }
        return render(request , 'shop/search_products.html' , context)'''


class SearchNamesView(ListView):
    """Product search by name in DB."""
    model = Product
    template_name = 'shop/search_names.html'

    def get_queryset(self):  # новый
        query = self.request.GET.get('q')
        object_list = Product.objects.filter(
            name=query
            #Q(name__icontains=query) | Q(description__icontains=query)
        )
        return object_list

shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.title }}{% else %}Товари{% endif %}
{% endblock %}
{% block content %}
    <div class="product-detail">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        <h2>{{ product.name }}</h2>
        <h5>Категорія: <a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h5>
        <p class="price">Вартість: {{ product.price }} грн.</p>
            <form action="{% url "shopping_cart:cart_add" product.id %}" method="post">
                {{ cart_product_form }}
                {% csrf_token %}
                <input type="submit" value="Добавити у кошик">
            </form>
        <h5>Опис товару:  </h5>
        <h6>{{ product.description|linebreaks }} </h6>
    </div>


    {% with comments.count as total_comments %}
        <h5>Товар має {{ total_comments }} відгуків </h5>
    {% endwith %}

    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Коментар {{ forloop.counter }} від {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p> Поки не має відгуків. </p>
    {% endfor %}

    {% if new_comment %}
        <h5>Ваш відгук додано</h5>
    {% else %}

        {% if user.is_authenticated %}
        <h5>Ви можете додати відгук</h5>
        <form action="." method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Додати відгук"></p>
        </form>
        {% else %}
            <h7>Для додавання відгуків ви маєте авторизуватися</h7>
        {% endif %}

    {% endif %}

{% endblock %}

shop/templates/shop/product/detail_v1.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.title }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
    <div class="product-detail">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        <h1>{{ product.name }}</h1>
        <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
        <p class="price">${{ product.price }}</p>
        {{ product.description|linebreaks }}
    </div>
{% endblock %}

shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if category %} ЩО ТАКЕ-1 {{ category.name }}{% else %}Товари{% endif %}
{% endblock %}
{% block content %}
    <div id="sidebar">
        <h4>Категорії</h4>
        <ul>
            <li {% if not category %}class="selected"{% endif %}>
                <a href="{% url "shop:product_list" %}">Всі категорії</a>
            </li>
            {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div id="main" class="product-list">
        <h4>{% if category %} Товари категорії: {{ category.name }}{% else %} Всі товари {% endif %}</h3>
        {% for product in products %}
            <div class="item">
                <a href="{{ product.get_absolute_url }}">
                    <img src="{% if product.image %} {{ product.image.url }} {% else %}{% static "img/no_image.png" %}{% endif %}">
                </a>
                <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
                {{ product.price }} грн.
            </div>
        {% endfor %}
    </div>
{% endblock %}