myshop/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls import include
#from django.conf.urls import include, url

from django.conf import settings
from django.conf.urls.static import static

from users import views as user_views
from django.contrib.auth import views as auth_views

from shop import views as shop_views

from django.urls import re_path
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    #path(r'^admin/', include(admin.site.urls)),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/',
         auth_views.LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('logout/',
         auth_views.LogoutView.as_view(template_name='users/logout.html'),
         name='logout'),
    path(r'cart/', include('shopping_cart.urls')),
    #url(r'^cart/', include('cart.urls', namespace='cart')),
    path(r'orders/', include('shopping_orders.urls')),
    #path(r'^orders/', include('shopping_orders.urls')),
    #url(r'^orders/', include('orders.urls', namespace='orders')),
    path(r'', include('shop.urls')),
    #path(r'', include('shop.urls', namespace='shop')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#for working image at Debug=False
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT,}),]

shop/urls.py
from django.contrib import admin
from django.urls import path, include

#from django.conf.urls import url
from . import views

app_name = 'shop'
urlpatterns = [
    path(r'', views.product_list, name='product_list'),
    path(r'about/', views.about, name='about'),
    #path(r'^$', views.product_list, name='product_list'),
    path(r'(?P<category_slug>[-\w]+)/',
        views.product_list,
        name='product_list_by_category'),
    path(r'(?P<id>\d+)/(?P<slug>[-\w]+)/',
        views.product_detail,
        name='product_detail'),
    path('Search/', views.Search.as_view(), name='Search'),
    #path('SearchProducts/', views.SearchProducts.as_view(), name='SearchProducts'),
    path('SearchNames/', views.SearchNamesView.as_view(), name='SearchNames'),

]

'''
urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list,
        name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),
]
'''

shopping_cart/urls.py
#from django.conf.urls import url
from django.urls import path, include
from . import views


app_name = 'shopping_cart'
urlpatterns = [
    path(r'', views.cart_detail, name='cart_detail'),
    path(r'add/(?P<product_id>\d+)/', views.cart_add, name='cart_add'),
    #path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    path(r'remove/(?P<product_id>\d+)/', views.cart_remove, name='cart_remove'),
    #path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

shopping_orders/urls.py
#from django.conf.urls import url
from django.urls import path, include
from . import views


app_name = 'shopping_orders'
urlpatterns = [
    path(r'create/', views.order_create, name='order_create'),
    #path(r'^create/$', views.order_create, name='order_create'),
]

shopping_cart/models.py
from django.db import models

# Create your models here.

shopping_cart/forms.py
from django import forms
from django.core.validators import ValidationError

#PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]


def check_quantity(value):
    print(f'check quantity: {value}')
    if value <= 0:
        raise ValidationError("має бути позитивне число")


class CartAddProductForm(forms.Form):
    #quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label = "Кількість" )
    quantity = forms.DecimalField(max_digits=5,
                                  decimal_places=0,
                                  label = "Кількість",
                                  help_text="Введіть необхідну кількість одиниць товару",
                                  validators=[check_quantity],
                                  )
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

shopping_cart/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST #Дозволяємо лише POST запити
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    else:
        print(f'errrrrooooorrrrreeee: quantity <=0 ')
        #return HttpResponse('Invalid login')

    return redirect('shopping_cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('shopping_cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'shopping_cart/detail.html', {'cart': cart})

shopping_cart/templates/shopping_cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    Ваш кошик замовлення
{% endblock %}
{% block content %}
    <h1>Ваш кошик замовлення</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Зображення</th>
            <th>Назва</th>

            <th>Кількіть</th>
            <th>Вартість</th>
            <th>Сума</th>
            <th>Видалити</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="
                                {% if product.image %}
                                    {{ product.image.url }}
                                {% else %}
                                    {% static 'img/no_image.png' %}
                                {% endif %}">
                        </a>
                    </td>
                    <td><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></td>

                    <td>{{ item.quantity }}</td>
                    <td class="num">{{ item.price }} грн</td>
                    <td class="num">{{ item.total_price }} грн</td>
                    <td><a href="{% url 'shopping_cart:cart_remove' product.id%}">Видалити</a></td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Загальна вартість замовлення </td>
            <td colspan="4"></td>
            <td class="num">{{ cart.get_total_price }} грн</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
      <ul class="list-group">
        <a href="{% url 'shop:product_list' %}" class="button light">Продовжити покупки</a>
        {% if user.is_authenticated %}
          <li class="list-group-item list-group-item-light">
          <a href="{% url 'shopping_orders:order_create' %}" class="button">
             Оформлення замовлення
          </a>
          </li>
        {% else %}
          <li class="list-group-item list-group-item-light">
              Для оформлення замовлення необхідно авторизуватися
          </li>
        {% endif %}
      </ul>
    </p>
{% endblock %}


                {% if user.is_authenticated %}
                  <li class="list-group-item list-group-item-light">
            	    <a class="nav-item nav-link" href="{% url 'profile' %}">Профіль</a>
                  </li>
                  <li class="list-group-item list-group-item-light">
            	    <a class="nav-item nav-link" href="{% url 'logout' %}">Вихід</a>
                  </li>
          	    {% else %}
                  <li class="list-group-item list-group-item-light">
            	    <a class="nav-item nav-link" href="{% url 'login' %}">Вхід</a>
                  </li>
                  <li class="list-group-item list-group-item-light">
            	    <a class="nav-item nav-link" href="{% url 'register' %}">Реєстрація</a>
                  </li>
          	    {% endif %}