myshop/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls import include
#from django.conf.urls import include, url

from django.conf import settings
from django.conf.urls.static import static

from users import views as user_views
from django.contrib.auth import views as auth_views

from shop import views as shop_views

from django.urls import re_path
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    #path(r'^admin/', include(admin.site.urls)),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/',
         auth_views.LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('logout/',
         auth_views.LogoutView.as_view(template_name='users/logout.html'),
         name='logout'),
    path(r'cart/', include('shopping_cart.urls')),
    #url(r'^cart/', include('cart.urls', namespace='cart')),
    path(r'orders/', include('shopping_orders.urls')),
    #path(r'^orders/', include('shopping_orders.urls')),
    #url(r'^orders/', include('orders.urls', namespace='orders')),
    path(r'', include('shop.urls')),
    #path(r'', include('shop.urls', namespace='shop')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#for working image at Debug=False
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT,}),]

shop/urls.py
from django.contrib import admin
from django.urls import path, include

#from django.conf.urls import url
from . import views

app_name = 'shop'
urlpatterns = [
    path(r'', views.product_list, name='product_list'),
    path(r'about/', views.about, name='about'),
    #path(r'^$', views.product_list, name='product_list'),
    path(r'(?P<category_slug>[-\w]+)/',
        views.product_list,
        name='product_list_by_category'),
    path(r'(?P<id>\d+)/(?P<slug>[-\w]+)/',
        views.product_detail,
        name='product_detail'),
    path('Search/', views.Search.as_view(), name='Search'),
    #path('SearchProducts/', views.SearchProducts.as_view(), name='SearchProducts'),
    path('SearchNames/', views.SearchNamesView.as_view(), name='SearchNames'),

]

'''
urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list,
        name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),
]
'''

shopping_cart/urls.py
#from django.conf.urls import url
from django.urls import path, include
from . import views


app_name = 'shopping_cart'
urlpatterns = [
    path(r'', views.cart_detail, name='cart_detail'),
    path(r'add/(?P<product_id>\d+)/', views.cart_add, name='cart_add'),
    #path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    path(r'remove/(?P<product_id>\d+)/', views.cart_remove, name='cart_remove'),
    #path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

shop/models.py
from django.db import models

# Create your models here.
from django.urls import reverse


class Category(models.Model):
    """Category of goods our shop."""
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категорія'
        verbose_name_plural = 'Категорії'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])


class Product(models.Model):
    """Detail description of goods."""
    category = models.ForeignKey(Category,
                                 on_delete=models.CASCADE,
                                 related_name='products')
    name = models.CharField(max_length=50,
                            db_index=True,
                            verbose_name="Найменування")
    slug = models.SlugField(max_length=200,
                            db_index=True)  #аліас продукта(його URL)?
    code = models.PositiveIntegerField(blank = True,
                                       verbose_name="артикул")
    stock = models.PositiveIntegerField(default=100,
                                        verbose_name="кількість товара") #default=100 for 'simply inputing'
    available = models.BooleanField(default=True,
                                    verbose_name="наявність товара")
    price = models.DecimalField(max_digits = 8,
                                decimal_places = 2,
                                verbose_name="ціна товара") #222222.22
    description = models.TextField(max_length=2000,
                                   blank = True,
                                   verbose_name="опис товару")
    image = models.ImageField(upload_to='media',
    #image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank = True,
                              verbose_name="фотографія товара")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    '''integer_field           = models.IntegerField()
    positive_small_field    = models.PositiveSmallIntegerField()
    big_integer_field       = models.BigIntegerField()
    float_field             = models.FloatField()
    binary_field            = models.BinaryField()
    file_field              = models.FileField(upload_to = 'file')'''
    #onsale = models.ManyToManyField(Sale)
    #user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ('name',)
        # задаємо індекс для полів, тя будемо запитувати продукти за допомогою id та slug
        index_together = (('id', 'slug'),)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товари'

    def __str__(self):
        return f"Назва : {self.name} Артикул : {self.code} Наявність : {self.available}"

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])


class CommentModel(models.Model):
    """Users anonimus comment of goods."""
    product = models.ForeignKey(Product,
                             on_delete=models.CASCADE,
                             related_name='comments',
                             verbose_name="коментар товару")
    #name = models.CharField(max_length=80)
    #email = models.EmailField()
    body = models.TextField(verbose_name="відгук")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True) #for moderate comment

    class Meta:
        ordering = ('created',)
        verbose_name = 'Відгук'
        verbose_name_plural = 'Відгуки'

    def __str__(self):
        return f'Відну авторизованого користувача до {self.product}'


'''
class User(models.Model):
    name = models.CharField(max_length=10, blank = True, verbose_name = "Ім'я")
    surname = models.CharField(max_length=15, blank = True, verbose_name="Прізвище", null=True)
    email = models.EmailField(blank = True)
    date_time_buy = models.DateTimeField(auto_now_add=False, verbose_name="дата покупки", null=True)
    LastBuy = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"Ім'я : {self.name} Прізвище : {self.surname}"

    class Meta:
        verbose_name = "Користувач"
        verbose_name_plural = "Користувачі"
'''

shop/forms.py
from django import forms

from .models import CommentModel


class CommentForm(forms.ModelForm):
    """Form of comment goods."""
    class Meta:
        model = CommentModel
        fields = ('body', )
        #fields = ('name', 'email', 'body')

shop/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import get_object_or_404
from .models import Category, Product, CommentModel
from shopping_cart.forms import CartAddProductForm

from .forms import CommentForm
#for search (from DZ_CBS33)
from django.views.generic import TemplateView, ListView
from django.db.models import Q

def product_list(request, category_slug=None):
    """ Загальний список (наявних) товарів."""
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


'''def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    return render(request,
                  'shop/product/detail.html',
                  {'product': product})'''


def product_detail(request, id, slug):
    """ Опис (наявної) одиниці товару."""
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()  #кнопка дадати в кошик

    comments = product.comments.filter(active=True)  #використовуємо related_name з моделі CommentModel
    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        print(f'test comment1: {comment_form}')
        if comment_form.is_valid():
            print(f'test comment2: {comment_form}')
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.product = product
            # Save the comment to the database
            new_comment.save()
            print(f'test comment3: {comment_form}')
    else:
        comment_form = CommentForm() # for metod GET

    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form,
                   'comments': comments,
                   'comment_form': comment_form})


def about(request):
    """Publication of general information about project/company"""
    return render(request,'shop/about.html', {})

#(from DZ_CBS33)
class Search(TemplateView):
    """Product search by keyword (part of) in name, description DB (will be update for many fields)."""
    template_name = 'shop/search.html'
    def post(self , request):
        query = request.POST['search']
        result_list  = Product.objects.filter(Q(name__icontains=query) | Q(description__icontains=query))
        #result_list = Product.objects.filter(name=query)

        if result_list.count() != 0:
            context = {
                'result_list': result_list,
                'query': query,
            }
        else:
            context ={
                'empty': "Нічого не найдено :(",
                'query': query,
            }
        return render(request , 'shop/search_results.html' , context)


'''class SearchProducts(TemplateView):
    """Product search by name in DB."""
    template_name = 'shop/base.html'
    def post(self , request):
        query = request.POST['search']
        result_list  = Product.objects.filter(name=query)
        if result_list.count() != 0:
            context = {
                'result_list': result_list,
                'query': query,
            }
        else:
            context ={
                'empty': "Нічого не найдено :(",
                'query': query,
            }
        return render(request , 'shop/search_products.html' , context)'''


class SearchNamesView(ListView):
    """Product search by name in DB."""
    model = Product
    template_name = 'shop/search_names.html'

    def get_queryset(self):  # новый
        query = self.request.GET.get('q')
        object_list = Product.objects.filter(
            name=query
            #Q(name__icontains=query) | Q(description__icontains=query)
        )
        return object_list

shop/templates/shop/about.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    <h1> Інтернет магазин</h1>
{% endblock %}
{% block content %}
<h1> Інтернет магазин</h1>
<h4>«Курсовые проекты с использованием фреймворка Django»</h4>
<h6>Цель: Продемонстрировать навыки создания Django приложений</h6>
<h6> Обязательные языки/технологии/библиотеки: Python, Django</h6>
<h5> Задание 1 </h5>
<h6> Создайте Django приложение, интернет магазин.</h6>
<h5>Требования:</h5>
<li>Создать страницу, на которой будут выводиться все товары</li>
<li>Создать страницу, на которой будут выводиться информация об одном товаре.</li>
<li>Добавьте возможность авторизированному пользователю оставлять отзыв/комментарий о товаре.</li>
<li>Страница регистрация/авторизация</li>
<li>Фильтрование по категориям товаров</li>
<li>Добавить возможность поиска товара на странице</li>
<li>Создать страницу для оформления заказа для авторизированных пользователей (без платежной системы)</li>

<h5> Дополнительные требования</h5>
<li>- Возможность подписки на новости(celery)</li>
<li>- Команда для загрузки с внешней БД(команда для manage.py)</li>
<li>- Просмотренные товары</li>
<li>Стилизация – на Ваше усмотрение.</li>
<h5>Важные моменты</h5>
<li>• Блокировка перехода по меню edit/delete/create если пользователь не авторизирован.

<li>• Использование SQL.</li>

{% endblock %}

shop/templates/shop/aboutWorkDeploy.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    <h1> Інтернет магазин</h1>
{% endblock %}
{% block content %}
<h1> Інтернет магазин</h1>
<h4>«Курсовые проекты с использованием фреймворка Django»</h4>
<h6>Цель: Продемонстрировать навыки создания Django приложений</h6>
<h6> Обязательные языки/технологии/библиотеки: Python, Django</h6>
<h5> Задание 1 </h5>
<h6> Создайте Django приложение, интернет магазин.</h6>
<h5>Требования:</h5>
<li>Создать страницу, на которой будут выводиться все товары</li>
<li>Создать страницу, на которой будут выводиться информация об одном товаре.</li>
<li>Добавьте возможность авторизированному пользователю оставлять отзыв/комментарий о товаре.</li>
<li>Страница регистрация/авторизация</li>
<li>Фильтрование по категориям товаров</li>
<li>Добавить возможность поиска товара на странице</li>
<li>Создать страницу для оформления заказа для авторизированных пользователей (без платежной системы)</li>

<h5> Дополнительные требования</h5>
<li>- Возможность подписки на новости(celery)</li>
<li>- Команда для загрузки с внешней БД(команда для manage.py)</li>
<li>- Просмотренные товары</li>
<li>Стилизация – на Ваше усмотрение.</li>
<h5>Важные моменты</h5>
<li>• Блокировка перехода по меню edit/delete/create если пользователь не авторизирован.

<li>• Использование SQL.</li>

{% endblock %}

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Обязательные мета-теги -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap, иконки и шрифт -->
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
     <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900italic,900' rel='stylesheet' type='text/css'>

     <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>

    {% if title %}
        <title>Shop {{ title }}</title>
    {% else %}
        <title>internet shop Python & Django</title>
    {% endif %}
</head>
<body>
    <header class="site-header">


    </header>
    <main role="main" class="container">
      <div class="row">

        <div class="col-md-2">
            <div class="content-section">
            <h3> Тут може бути Ваша реклама</h3>
            </div>
        </div>

        <div class="col-md-8">
          {% block content %}{% endblock %}
        </div>

        <div class="col-md-2">
          <div class="content-section">
              <h1></h1>
            <a class="navbar-brand mr-4" href="{% url 'shop:about' %}"><i class='bx bxs-rocket bx-tada-hover'></i> Shop Python & Django </a>
            <p class='text-muted'> Don't give up :)
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">
                  <a class="nav-item nav-link " href="{% url 'shop:product_list' %}">Головна</a>
                </li>
                <li class="list-group-item list-group-item-light">
                  <a class="nav-item nav-link " href="{% url 'shopping_cart:cart_detail' %}">Кошик</a>
                </li>

                  <li class="list-group-item list-group-item-light">
            	    <a class="nav-item nav-link" href="{% url 'shop:Search' %}">Розширений пошук</a>
                  </li>

                {% if user.is_authenticated %}
                  <li class="list-group-item list-group-item-light">
            	    <a class="nav-item nav-link" href="{% url 'profile' %}">Профіль</a>
                  </li>
                  <li class="list-group-item list-group-item-light">
            	    <a class="nav-item nav-link" href="{% url 'logout' %}">Вихід</a>
                  </li>
          	    {% else %}
                  <li class="list-group-item list-group-item-light">
            	    <a class="nav-item nav-link" href="{% url 'login' %}">Вхід</a>
                  </li>
                  <li class="list-group-item list-group-item-light">
            	    <a class="nav-item nav-link" href="{% url 'register' %}">Реєстрація</a>
                  </li>
          	    {% endif %}

                    <h6>швидкий пошук</h6>

                    <form action="{% url 'shop:SearchNames' %}" method="get">
                      <input name="q" type="text" placeholder="Пошук за найменуванням товару...">
                    </form>

                </form>

              </ul>
            </p>
          </div>
        </div>
      </div>


    </main>
    <!-- Футер закреплен внизу, независимо от количества постов на странице -->
    <footer class="text-center bg-dark">
      <p><a href="{% url 'shop:product_list' %}">© Shop Python & Django 2022</a></p>
    </footer>

</body>
</html>
© 2022 P&D, Inc.

shop/templates/shop/baseOld.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}My shop {% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
</head>
<body>
<div id="header">
    <a href="/" class="logo">Інтернет магазин " Python & Django "</a>
</div>
<div id="subheader">
    <div class="cart">
        {% with total_items=cart|length %}
            {% if cart|length > 0 %}
                Ваш кошик:
                <a href="{% url "shopping_cart:cart_detail" %}">
                    товарів {{ total_items }} шт. ,
                    на суму {{ cart.get_total_price }} грн.
                </a>
            {% else %}
                Ваш кошик пустий.
            {% endif %}
        {% endwith %}
    </div>
</div>


<div id="content">

    {% if messages %}
        	{% for message in messages %}
          	<div class="alert alert-{{ message.tags }}">
            	{{ message }}
          	</div>
        	{% endfor %}
    {% endif %}

    {% block content %}
    {% endblock %}
</div>

</body>
</html>

shop/templates/shop/baseVar2.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Обязательные мета-теги -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap, иконки и шрифт -->
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
     <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900italic,900' rel='stylesheet' type='text/css'>

     <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>

    {% if title %}
        <title>Shop {{ title }}</title>
    {% else %}
        <title>internet shop Python & Django</title>
    {% endif %}
</head>
<body>
    <header class="site-header">


    </header>
    <main role="main" class="container">
      <div class="row">

        <div class="col-md-2">
            <div class="content-section">
            <h3> Тут може бути Ваша реклама</h3>
            </div>
        </div>

        <div class="col-md-8">
          {% block content %}{% endblock %}
        </div>

        <div class="col-md-2">
          <div class="content-section">
              <h1></h1>
            <a class="navbar-brand mr-4" href="{% url 'shop:about' %}"><i class='bx bxs-rocket bx-tada-hover'></i> Shop Python & Django </a>
            <p class='text-muted'> Don't give up :)
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">
                  <a class="nav-item nav-link " href="{% url 'shop:product_list' %}">Головна</a>
                </li>
                <li class="list-group-item list-group-item-light">
                  <a class="nav-item nav-link " href="{% url 'shopping_cart:cart_detail' %}">Кошик</a>
                </li>

                  <li class="list-group-item list-group-item-light">
            	    <a class="nav-item nav-link" href="{% url 'shop:Search' %}">Розширений пошук</a>
                  </li>

                {% if user.is_authenticated %}
                  <li class="list-group-item list-group-item-light">
            	    <a class="nav-item nav-link" href="{% url 'profile' %}">Профіль</a>
                  </li>
                  <li class="list-group-item list-group-item-light">
            	    <a class="nav-item nav-link" href="{% url 'logout' %}">Вихід</a>
                  </li>
          	    {% else %}
                  <li class="list-group-item list-group-item-light">
            	    <a class="nav-item nav-link" href="{% url 'login' %}">Вхід</a>
                  </li>
                  <li class="list-group-item list-group-item-light">
            	    <a class="nav-item nav-link" href="{% url 'register' %}">Реєстрація</a>
                  </li>
          	    {% endif %}


                  <form action="{% url 'shop:SearchProducts' %}" method = 'post'>
                    {% csrf_token %}
                    <label for="">Введіть назву товару</label>
                    <input  name = 'search' type="text">
                  </form>


                    <h1>пошук3</h1>

                    <form action="{% url 'shop:SearchResults' %}" method="get">
                      <input name="q" type="text" placeholder="Пошук товару...">
                    </form>

                </form>

              </ul>
            </p>
          </div>
        </div>
      </div>


    </main>
    <!-- Футер закреплен внизу, независимо от количества постов на странице -->
    <footer class="text-center bg-dark">
      <p><a href="{% url 'shop:product_list' %}">© Shop Python & Django 2022</a></p>
    </footer>

</body>
</html>
© 2022 P&D, Inc.

shop/templates/shop/baseWorkDeploy.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Обязательные мета-теги -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap, иконки и шрифт -->
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
     <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900italic,900' rel='stylesheet' type='text/css'>
     <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">
     <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>

    {% if title %}
        <title>Shop {{ title }}</title>
    {% else %}
        <title>internet shop Python & Django</title>
    {% endif %}
</head>
<body>
    <header class="site-header">


    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
              <h1></h1>
            <a class="navbar-brand mr-4" href="{% url 'shop:about' %}"><i class='bx bxs-rocket bx-tada-hover'></i> Shop Python & Django </a>
            <p class='text-muted'> Don't give up :)
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">
                  <a class="nav-item nav-link " href="{% url 'shop:product_list' %}">Головна</a>
                </li>
                <li class="list-group-item list-group-item-light">
                  <a class="nav-item nav-link " href="{% url 'shopping_cart:cart_detail' %}">Кошик</a>
                </li>

                {% if user.is_authenticated %}
                  <li class="list-group-item list-group-item-light">
            	    <a class="nav-item nav-link" href="{% url 'profile' %}">Профіль</a>
                  </li>
                  <li class="list-group-item list-group-item-light">
            	    <a class="nav-item nav-link" href="{% url 'logout' %}">Вихід</a>
                  </li>
          	    {% else %}
                  <li class="list-group-item list-group-item-light">
            	    <a class="nav-item nav-link" href="{% url 'login' %}">Вхід</a>
                  </li>
                  <li class="list-group-item list-group-item-light">
            	    <a class="nav-item nav-link" href="{% url 'register' %}">Реєстрація</a>
                  </li>
          	    {% endif %}
              </ul>
            </p>
          </div>
        </div>
      </div>

    </main>
    <!-- Футер закреплен внизу, независимо от количества постов на странице -->
    <footer class="text-center bg-dark">
      <p><a href="{% url 'shop:product_list' %}">© Shop Python & Django 2022</a></p>
    </footer>

    <!-- Дополнительные скрипты JavaScript -->
    <!-- Сначала jQuery, затем Popper.js, последним Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>
© 2022 P&D, Inc.

shop/templates/shop/search.html
<!-- inheritans example-->

{% extends 'shop/base.html' %}

{% block content %}
    <h3>Пошук товару за назвою або описом.</h3>

    <h2></h2>
    <form action="" method = 'post'>
        {% csrf_token %}
        <label for="">Введіть повну (або частину) найменування  товару або ключове слово з його опису</label>
        <input  name = 'search' type="text">
        <button type="submit">Знайти</button>
    </form>

{% endblock content %}

shop/templates/shop/search_names.html
{% extends 'shop/base.html' %}
{% load static %}
{% block content %}
<h3>Результат пошуку</h3>

<ul>
  {% for product in object_list %}

  {% if product.available %}

    <li>
      <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
      артикул: {{ product.code }}
      вартість: {{ product.price }} грн
      категорія: {{ product.category }}
      <br>
    </li>

  {% else %}
    <li>
      <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
      артикул: {{ product.code }}
      вартість: {{ product.price }} грн
      категорія: {{ product.category }}
      наразі відсутній
      <br>
    </li>
  {% endif %}

  {% empty %}
    <td>Даного товару поки що немає у магазині.</td>
  {% endfor %}
</ul>

{% endblock %}